name: Test msg

on:
  workflow_dispatch:
    

jobs:
  build:
    name: Test msg
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Inline
      run: |
            curl -X POST \
            https://api.telegram.org/bot${{secrets.TELEGRAM_BOT_TOKEN}}/sendMessage \
            -d chat_id=@Mizumo_prjkt \
            -d text="This is a test dummy of MizKernel under type: ${{ github.event.inputs.version }} %0A%0A The source code kernel is available at: https://github.com/MizProject/MizKernel-GalaxyA12s [...] \
            -d reply_markup='{"inline_keyboard": [ \
                [{"text": "Check Releases of this CI Result", "url": "https://github.com/MizProject/MizKernel-Kitchen/releases/tag/${{github.run_id}}"}],
                [{"text": "Download Kernel Image", "url": "https://github.com/MizProject/MizKernel-Kitchen/releases/download/${{github.run_id}}/Image"}],
                [{"text": "Download Boot Image", "url": "https://github.com/MizProject/MizKernel-Kitchen/releases/download/${{github.run_id}}/boot.img"}],
                [{"text": "Download TWRP Zip", "url": "https://github.com/MizProject/MizKernel-Kitchen/releases/download/${{github.run_id}}/MizKernel-${{github.run_id}}-twrp.zip"}]
            ]}'
